# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn pkg
      - save_cache:
          paths:
            - lib
            - binaries
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
  deploy-npm:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish
  deploy-release:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: go get github.com/tcnksm/ghr
      - run: ghr --username $CIRCLE_PROJECT_USERNAME $CIRCLE_TAG binaries/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy-npm:
          requires:
            - build
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
      - deploy-release:
          requires:
            - build
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
