version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    ignored_updates:
      - match:
          dependency_name: '@types/node'
          version_requirement: '>= 9.0.0'
