version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    ignored_updates:
      - match:
          dependency_name: '@types/node'
          version_requirement: '>= 13.0.0'
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
    version_requirement_updates: increase_versions
